AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch Server Monitoring System

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
  
  DefaultSlackWebhook:
    Type: String
    Description: Default Slack webhook URL
    NoEcho: true
  
  YC2SlackWebhook:
    Type: String
    Description: YC2 Slack webhook URL
    NoEcho: true
    Default: ""
  
  YC3SlackWebhook:
    Type: String
    Description: YC3 Slack webhook URL
    NoEcho: true
    Default: ""
  
  KeepaSlackWebhook:
    Type: String
    Description: Keepa Slack webhook URL
    NoEcho: true
    Default: ""
  
  DbcSlackWebhook:
    Type: String
    Description: DBC Slack webhook URL
    NoEcho: true
    Default: ""
  
  LaborHackSlackWebhook:
    Type: String
    Description: Labor-hack Slack webhook URL
    NoEcho: true
    Default: ""

  # Server Domain Names
  YC2Domain:
    Type: String
    Description: YC2 server domain name
    Default: your-yc2-domain.com

  YC3Domain:
    Type: String
    Description: YC3 server domain name
    Default: your-yc3-domain.com

  KeepaDomain:
    Type: String
    Description: Keepa server domain name
    Default: your-keepa-domain.com

  DbcDomain:
    Type: String
    Description: DBC server domain name
    Default: your-dbc-domain.com

  LaborHackDomain:
    Type: String
    Description: Labor Hack server domain name
    Default: your-labor-hack-domain.com

  # Server Paths
  YC2Path:
    Type: String
    Description: YC2 server health check path
    Default: /

  YC3Path:
    Type: String
    Description: YC3 server health check path
    Default: /

  KeepaPath:
    Type: String
    Description: Keepa server health check path
    Default: /

  DbcPath:
    Type: String
    Description: DBC server health check path
    Default: /

  LaborHackPath:
    Type: String
    Description: Labor Hack server health check path
    Default: /

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Conditions:
  HasYC2Webhook: !Not [!Equals [!Ref YC2SlackWebhook, ""]]
  HasYC3Webhook: !Not [!Equals [!Ref YC3SlackWebhook, ""]]
  HasKeepaWebhook: !Not [!Equals [!Ref KeepaSlackWebhook, ""]]
  HasDbcWebhook: !Not [!Equals [!Ref DbcSlackWebhook, ""]]
  HasLaborHackWebhook: !Not [!Equals [!Ref LaborHackSlackWebhook, ""]]

Resources:
  # Regular OK Status Check Function
  StatusCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-status-checker"
      CodeUri: ../src/
      Handler: status_checker.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Environment:
        Variables:
          DEFAULT_SLACK_WEBHOOK: !Ref DefaultSlackWebhook
          YC2_SLACK_WEBHOOK: !Ref YC2SlackWebhook
          YC3_SLACK_WEBHOOK: !Ref YC3SlackWebhook
          KEEPA_SLACK_WEBHOOK: !Ref KeepaSlackWebhook
          DBC_SLACK_WEBHOOK: !Ref DbcSlackWebhook
          LABOR_HACK_SLACK_WEBHOOK: !Ref LaborHackSlackWebhook
          YC2_HEALTH_CHECK_ID: !Ref YC2HealthCheck
          YC3_HEALTH_CHECK_ID: !Ref YC3HealthCheck
          KEEPA_HEALTH_CHECK_ID: !Ref KeepaHealthCheck
          DBC_HEALTH_CHECK_ID: !Ref DbcHealthCheck
          LABOR_HACK_HEALTH_CHECK_ID: !Ref LaborHackHealthCheck
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - route53:GetHealthCheck
                - route53:GetHealthCheckStatus
                - route53:ListHealthChecks
              Resource: '*'

  # SNS Topic for notifications
  MonitoringTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-system-alerts"
      DisplayName: System Monitoring Alerts

  # Lambda function for Slack notifications
  SlackNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-notification-handler"
      CodeUri: ../src/
      Handler: slack_notification.lambda_handler
      Environment:
        Variables:
          DEFAULT_SLACK_WEBHOOK: !Ref DefaultSlackWebhook
          YC2_SLACK_WEBHOOK: !Ref YC2SlackWebhook
          YC3_SLACK_WEBHOOK: !Ref YC3SlackWebhook
          KEEPA_SLACK_WEBHOOK: !Ref KeepaSlackWebhook
          DBC_SLACK_WEBHOOK: !Ref DbcSlackWebhook
          LABOR_HACK_SLACK_WEBHOOK: !Ref LaborHackSlackWebhook
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MonitoringTopic

  # Route 53 Health Checks
  YC2HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: !Ref YC2Path
        FullyQualifiedDomainName: !Ref YC2Domain
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${Environment}-server-001-health-check"
        - Key: Environment
          Value: !Ref Environment

  YC3HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: !Ref YC3Path
        FullyQualifiedDomainName: !Ref YC3Domain
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${Environment}-server-002-health-check"
        - Key: Environment
          Value: !Ref Environment

  KeepaHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: !Ref KeepaPath
        FullyQualifiedDomainName: !Ref KeepaDomain
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${Environment}-server-003-health-check"
        - Key: Environment
          Value: !Ref Environment

  DbcHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: !Ref DbcPath
        FullyQualifiedDomainName: !Ref DbcDomain
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${Environment}-server-004-health-check"
        - Key: Environment
          Value: !Ref Environment

  LaborHackHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: !Ref LaborHackPath
        FullyQualifiedDomainName: !Ref LaborHackDomain
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${Environment}-server-005-health-check"
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Alarms
  YC2HealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-server-001-health-check-failed"
      AlarmDescription: Server 001 health check failed
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref YC2HealthCheck
      AlarmActions:
        - !Ref MonitoringTopic
      OKActions:
        - !Ref MonitoringTopic

  YC3HealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-server-002-health-check-failed"
      AlarmDescription: Server 002 health check failed
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref YC3HealthCheck
      AlarmActions:
        - !Ref MonitoringTopic
      OKActions:
        - !Ref MonitoringTopic

  KeepaHealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-server-003-health-check-failed"
      AlarmDescription: Server 003 health check failed
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref KeepaHealthCheck
      AlarmActions:
        - !Ref MonitoringTopic
      OKActions:
        - !Ref MonitoringTopic

  DbcHealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-server-004-health-check-failed"
      AlarmDescription: Server 004 health check failed
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref DbcHealthCheck
      AlarmActions:
        - !Ref MonitoringTopic
      OKActions:
        - !Ref MonitoringTopic

  LaborHackHealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-server-005-health-check-failed"
      AlarmDescription: Server 005 health check failed
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref LaborHackHealthCheck
      AlarmActions:
        - !Ref MonitoringTopic
      OKActions:
        - !Ref MonitoringTopic

Outputs:
  MonitoringTopicArn:
    Description: SNS Topic ARN for monitoring alerts
    Value: !Ref MonitoringTopic
    Export:
      Name: !Sub "${Environment}-monitoring-topic-arn"
  
  SlackNotificationFunctionArn:
    Description: Slack notification Lambda function ARN
    Value: !GetAtt SlackNotificationFunction.Arn
    Export:
      Name: !Sub "${Environment}-slack-notification-function-arn"
