AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Server Monitoring System - Test Version

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]

Resources:
  # Route 53 Health Checks only for testing
  YC2HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: /
        FullyQualifiedDomainName: ycstg.lober-env-imp.work
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${Environment}-yc2-health-check"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  YC2HealthCheckId:
    Description: YC2 Health Check ID
    Value: !Ref YC2HealthCheck
    Export:
      Name: !Sub "${Environment}-yc2-health-check-id"
